/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminLecturesParams,
  GetAdminQuestionsParams,
  Lecture,
  PatchAdminGradesIdBody,
  PatchAdminLecturesIdBody,
  PatchAdminModulesIdBody,
  PatchAdminQuestionsBulkAssignLectureBody,
  PatchAdminSubjectsIdBody,
  PatchAdminTermsIdBody,
  PostAdminGradesBody,
  PostAdminLecturesBody,
  PostAdminModulesBody,
  PostAdminSubjectsBody,
  PostAdminTermsBody,
  Question
} from '.././model';

import { customAxios } from '.././mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const postAdminGrades = (
    postAdminGradesBody: PostAdminGradesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/grades`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminGradesBody, signal
    },
      options);
    }
  


export const getPostAdminGradesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext> => {

const mutationKey = ['postAdminGrades'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminGrades>>, {data: PostAdminGradesBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminGrades(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminGradesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminGrades>>>
    export type PostAdminGradesMutationBody = PostAdminGradesBody
    export type PostAdminGradesMutationError = unknown

    export const usePostAdminGrades = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminGrades>>,
        TError,
        {data: PostAdminGradesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminGradesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminGradesId = (
    id: string,
    patchAdminGradesIdBody: PatchAdminGradesIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/grades/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminGradesIdBody
    },
      options);
    }
  


export const getPatchAdminGradesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext> => {

const mutationKey = ['patchAdminGradesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminGradesId>>, {id: string;data: PatchAdminGradesIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminGradesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminGradesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminGradesId>>>
    export type PatchAdminGradesIdMutationBody = PatchAdminGradesIdBody
    export type PatchAdminGradesIdMutationError = unknown

    export const usePatchAdminGradesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminGradesId>>,
        TError,
        {id: string;data: PatchAdminGradesIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminGradesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminTerms = (
    postAdminTermsBody: PostAdminTermsBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/terms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminTermsBody, signal
    },
      options);
    }
  


export const getPostAdminTermsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext> => {

const mutationKey = ['postAdminTerms'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminTerms>>, {data: PostAdminTermsBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminTerms(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminTermsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminTerms>>>
    export type PostAdminTermsMutationBody = PostAdminTermsBody
    export type PostAdminTermsMutationError = unknown

    export const usePostAdminTerms = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminTerms>>,
        TError,
        {data: PostAdminTermsBody},
        TContext
      > => {

      const mutationOptions = getPostAdminTermsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminTermsId = (
    id: string,
    patchAdminTermsIdBody: PatchAdminTermsIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/terms/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminTermsIdBody
    },
      options);
    }
  


export const getPatchAdminTermsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext> => {

const mutationKey = ['patchAdminTermsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminTermsId>>, {id: string;data: PatchAdminTermsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminTermsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminTermsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminTermsId>>>
    export type PatchAdminTermsIdMutationBody = PatchAdminTermsIdBody
    export type PatchAdminTermsIdMutationError = unknown

    export const usePatchAdminTermsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminTermsId>>,
        TError,
        {id: string;data: PatchAdminTermsIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminTermsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminModules = (
    postAdminModulesBody: PostAdminModulesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/modules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminModulesBody, signal
    },
      options);
    }
  


export const getPostAdminModulesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext> => {

const mutationKey = ['postAdminModules'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminModules>>, {data: PostAdminModulesBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminModules(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminModulesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminModules>>>
    export type PostAdminModulesMutationBody = PostAdminModulesBody
    export type PostAdminModulesMutationError = unknown

    export const usePostAdminModules = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminModules>>,
        TError,
        {data: PostAdminModulesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminModulesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminModulesId = (
    id: string,
    patchAdminModulesIdBody: PatchAdminModulesIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/modules/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminModulesIdBody
    },
      options);
    }
  


export const getPatchAdminModulesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext> => {

const mutationKey = ['patchAdminModulesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminModulesId>>, {id: string;data: PatchAdminModulesIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminModulesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminModulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminModulesId>>>
    export type PatchAdminModulesIdMutationBody = PatchAdminModulesIdBody
    export type PatchAdminModulesIdMutationError = unknown

    export const usePatchAdminModulesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminModulesId>>,
        TError,
        {id: string;data: PatchAdminModulesIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminModulesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminSubjects = (
    postAdminSubjectsBody: PostAdminSubjectsBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/subjects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminSubjectsBody, signal
    },
      options);
    }
  


export const getPostAdminSubjectsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext> => {

const mutationKey = ['postAdminSubjects'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminSubjects>>, {data: PostAdminSubjectsBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminSubjects(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminSubjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminSubjects>>>
    export type PostAdminSubjectsMutationBody = PostAdminSubjectsBody
    export type PostAdminSubjectsMutationError = unknown

    export const usePostAdminSubjects = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminSubjects>>,
        TError,
        {data: PostAdminSubjectsBody},
        TContext
      > => {

      const mutationOptions = getPostAdminSubjectsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminSubjectsId = (
    id: string,
    patchAdminSubjectsIdBody: PatchAdminSubjectsIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/subjects/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminSubjectsIdBody
    },
      options);
    }
  


export const getPatchAdminSubjectsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext> => {

const mutationKey = ['patchAdminSubjectsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminSubjectsId>>, {id: string;data: PatchAdminSubjectsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminSubjectsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminSubjectsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminSubjectsId>>>
    export type PatchAdminSubjectsIdMutationBody = PatchAdminSubjectsIdBody
    export type PatchAdminSubjectsIdMutationError = unknown

    export const usePatchAdminSubjectsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminSubjectsId>>,
        TError,
        {id: string;data: PatchAdminSubjectsIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminSubjectsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminQuestions = (
    params?: GetAdminQuestionsParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Question[]>(
      {url: `/admin/questions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminQuestionsQueryKey = (params?: GetAdminQuestionsParams,) => {
    return [
    `/admin/questions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminQuestionsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminQuestionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminQuestions>>> = ({ signal }) => getAdminQuestions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminQuestions>>>
export type GetAdminQuestionsQueryError = unknown


export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params: undefined |  GetAdminQuestionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminQuestions>>,
          TError,
          Awaited<ReturnType<typeof getAdminQuestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminQuestions>>,
          TError,
          Awaited<ReturnType<typeof getAdminQuestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminQuestionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminQuestionsBulkAssignLecture = (
    patchAdminQuestionsBulkAssignLectureBody: PatchAdminQuestionsBulkAssignLectureBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/bulk-assign-lecture`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminQuestionsBulkAssignLectureBody
    },
      options);
    }
  


export const getPatchAdminQuestionsBulkAssignLectureMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>, TError,{data: PatchAdminQuestionsBulkAssignLectureBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>, TError,{data: PatchAdminQuestionsBulkAssignLectureBody}, TContext> => {

const mutationKey = ['patchAdminQuestionsBulkAssignLecture'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>, {data: PatchAdminQuestionsBulkAssignLectureBody}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminQuestionsBulkAssignLecture(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsBulkAssignLectureMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>>
    export type PatchAdminQuestionsBulkAssignLectureMutationBody = PatchAdminQuestionsBulkAssignLectureBody
    export type PatchAdminQuestionsBulkAssignLectureMutationError = unknown

    export const usePatchAdminQuestionsBulkAssignLecture = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>, TError,{data: PatchAdminQuestionsBulkAssignLectureBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>,
        TError,
        {data: PatchAdminQuestionsBulkAssignLectureBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsBulkAssignLectureMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminQuestionsId = (
    id: string,
    question: Question,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: question
    },
      options);
    }
  


export const getPatchAdminQuestionsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext> => {

const mutationKey = ['patchAdminQuestionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsId>>, {id: string;data: Question}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminQuestionsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsId>>>
    export type PatchAdminQuestionsIdMutationBody = Question
    export type PatchAdminQuestionsIdMutationError = unknown

    export const usePatchAdminQuestionsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsId>>,
        TError,
        {id: string;data: Question},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminQuestionsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminQuestionsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminQuestionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminQuestionsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminQuestionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminQuestionsId>>>
    
    export type DeleteAdminQuestionsIdMutationError = unknown

    export const useDeleteAdminQuestionsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminQuestionsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminQuestionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminLectures = (
    postAdminLecturesBody: PostAdminLecturesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/lectures`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminLecturesBody, signal
    },
      options);
    }
  


export const getPostAdminLecturesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminLectures>>, TError,{data: PostAdminLecturesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminLectures>>, TError,{data: PostAdminLecturesBody}, TContext> => {

const mutationKey = ['postAdminLectures'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminLectures>>, {data: PostAdminLecturesBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminLectures(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminLecturesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminLectures>>>
    export type PostAdminLecturesMutationBody = PostAdminLecturesBody
    export type PostAdminLecturesMutationError = unknown

    export const usePostAdminLectures = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminLectures>>, TError,{data: PostAdminLecturesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminLectures>>,
        TError,
        {data: PostAdminLecturesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminLecturesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminLectures = (
    params?: GetAdminLecturesParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Lecture[]>(
      {url: `/admin/lectures`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminLecturesQueryKey = (params?: GetAdminLecturesParams,) => {
    return [
    `/admin/lectures`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminLecturesQueryOptions = <TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(params?: GetAdminLecturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminLecturesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminLectures>>> = ({ signal }) => getAdminLectures(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminLecturesQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminLectures>>>
export type GetAdminLecturesQueryError = unknown


export function useGetAdminLectures<TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(
 params: undefined |  GetAdminLecturesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminLectures>>,
          TError,
          Awaited<ReturnType<typeof getAdminLectures>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminLectures<TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(
 params?: GetAdminLecturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminLectures>>,
          TError,
          Awaited<ReturnType<typeof getAdminLectures>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminLectures<TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(
 params?: GetAdminLecturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminLectures<TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(
 params?: GetAdminLecturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminLecturesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminLecturesId = (
    id: string,
    patchAdminLecturesIdBody: PatchAdminLecturesIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/lectures/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminLecturesIdBody
    },
      options);
    }
  


export const getPatchAdminLecturesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminLecturesId>>, TError,{id: string;data: PatchAdminLecturesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminLecturesId>>, TError,{id: string;data: PatchAdminLecturesIdBody}, TContext> => {

const mutationKey = ['patchAdminLecturesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminLecturesId>>, {id: string;data: PatchAdminLecturesIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminLecturesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminLecturesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminLecturesId>>>
    export type PatchAdminLecturesIdMutationBody = PatchAdminLecturesIdBody
    export type PatchAdminLecturesIdMutationError = unknown

    export const usePatchAdminLecturesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminLecturesId>>, TError,{id: string;data: PatchAdminLecturesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminLecturesId>>,
        TError,
        {id: string;data: PatchAdminLecturesIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminLecturesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    