/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminModulesParams,
  GetAdminProfile200,
  GetAdminQuestionsParams,
  GetAdminStudyUnitsParams,
  GetAdminSubjectsParams,
  GetAdminTermsParams,
  GetAdminUsers200Item,
  Grade,
  Module,
  PatchAdminGradesIdBody,
  PatchAdminModulesIdBody,
  PatchAdminProfileBody,
  PatchAdminQuestionsBulkAssignStudyUnitBody,
  PatchAdminQuestionsBulkAssignTelegramRangeBody,
  PatchAdminQuestionsBulkUnassignStudyUnitBody,
  PatchAdminStudyUnitsIdBody,
  PatchAdminSubjectsIdBody,
  PatchAdminTermsIdBody,
  PatchAdminUsersIdBody,
  PostAdminGradesBody,
  PostAdminModulesBody,
  PostAdminQuestionsBulkDelete200,
  PostAdminQuestionsBulkDeleteBody,
  PostAdminStudyUnitsBody,
  PostAdminStudyUnitsIdFilesBody,
  PostAdminStudyUnitsIdVideosBody,
  PostAdminSubjectsBody,
  PostAdminTermsBody,
  PostAdminUsersBody,
  Question,
  StudyUnit,
  Subject,
  Term
} from '.././model';

import { customAxios } from '.././mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const postAdminGrades = (
    postAdminGradesBody: PostAdminGradesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/grades`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminGradesBody, signal
    },
      options);
    }
  


export const getPostAdminGradesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext> => {

const mutationKey = ['postAdminGrades'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminGrades>>, {data: PostAdminGradesBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminGrades(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminGradesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminGrades>>>
    export type PostAdminGradesMutationBody = PostAdminGradesBody
    export type PostAdminGradesMutationError = unknown

    export const usePostAdminGrades = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminGrades>>,
        TError,
        {data: PostAdminGradesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminGradesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminGrades = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Grade[]>(
      {url: `/admin/grades`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminGradesQueryKey = () => {
    return [
    `/admin/grades`
    ] as const;
    }

    
export const getGetAdminGradesQueryOptions = <TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminGradesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminGrades>>> = ({ signal }) => getAdminGrades(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminGradesQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminGrades>>>
export type GetAdminGradesQueryError = unknown


export function useGetAdminGrades<TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminGrades>>,
          TError,
          Awaited<ReturnType<typeof getAdminGrades>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminGrades<TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminGrades>>,
          TError,
          Awaited<ReturnType<typeof getAdminGrades>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminGrades<TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminGrades<TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminGradesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminGradesId = (
    id: string,
    patchAdminGradesIdBody: PatchAdminGradesIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/grades/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminGradesIdBody
    },
      options);
    }
  


export const getPatchAdminGradesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext> => {

const mutationKey = ['patchAdminGradesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminGradesId>>, {id: string;data: PatchAdminGradesIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminGradesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminGradesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminGradesId>>>
    export type PatchAdminGradesIdMutationBody = PatchAdminGradesIdBody
    export type PatchAdminGradesIdMutationError = unknown

    export const usePatchAdminGradesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminGradesId>>,
        TError,
        {id: string;data: PatchAdminGradesIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminGradesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminGradesId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/grades/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminGradesIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminGradesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminGradesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminGradesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminGradesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminGradesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminGradesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminGradesId>>>
    
    export type DeleteAdminGradesIdMutationError = void

    export const useDeleteAdminGradesId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminGradesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminGradesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminGradesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminTerms = (
    postAdminTermsBody: PostAdminTermsBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/terms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminTermsBody, signal
    },
      options);
    }
  


export const getPostAdminTermsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext> => {

const mutationKey = ['postAdminTerms'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminTerms>>, {data: PostAdminTermsBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminTerms(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminTermsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminTerms>>>
    export type PostAdminTermsMutationBody = PostAdminTermsBody
    export type PostAdminTermsMutationError = unknown

    export const usePostAdminTerms = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminTerms>>,
        TError,
        {data: PostAdminTermsBody},
        TContext
      > => {

      const mutationOptions = getPostAdminTermsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminTerms = (
    params?: GetAdminTermsParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Term[]>(
      {url: `/admin/terms`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminTermsQueryKey = (params?: GetAdminTermsParams,) => {
    return [
    `/admin/terms`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminTermsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(params?: GetAdminTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminTermsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminTerms>>> = ({ signal }) => getAdminTerms(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminTermsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminTerms>>>
export type GetAdminTermsQueryError = unknown


export function useGetAdminTerms<TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(
 params: undefined |  GetAdminTermsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTerms>>,
          TError,
          Awaited<ReturnType<typeof getAdminTerms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminTerms<TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(
 params?: GetAdminTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTerms>>,
          TError,
          Awaited<ReturnType<typeof getAdminTerms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminTerms<TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(
 params?: GetAdminTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminTerms<TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(
 params?: GetAdminTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminTermsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminTermsId = (
    id: string,
    patchAdminTermsIdBody: PatchAdminTermsIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/terms/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminTermsIdBody
    },
      options);
    }
  


export const getPatchAdminTermsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext> => {

const mutationKey = ['patchAdminTermsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminTermsId>>, {id: string;data: PatchAdminTermsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminTermsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminTermsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminTermsId>>>
    export type PatchAdminTermsIdMutationBody = PatchAdminTermsIdBody
    export type PatchAdminTermsIdMutationError = unknown

    export const usePatchAdminTermsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminTermsId>>,
        TError,
        {id: string;data: PatchAdminTermsIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminTermsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminTermsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/terms/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminTermsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTermsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTermsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminTermsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminTermsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminTermsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminTermsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminTermsId>>>
    
    export type DeleteAdminTermsIdMutationError = void

    export const useDeleteAdminTermsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTermsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminTermsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminTermsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminModules = (
    postAdminModulesBody: PostAdminModulesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/modules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminModulesBody, signal
    },
      options);
    }
  


export const getPostAdminModulesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext> => {

const mutationKey = ['postAdminModules'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminModules>>, {data: PostAdminModulesBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminModules(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminModulesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminModules>>>
    export type PostAdminModulesMutationBody = PostAdminModulesBody
    export type PostAdminModulesMutationError = unknown

    export const usePostAdminModules = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminModules>>,
        TError,
        {data: PostAdminModulesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminModulesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminModules = (
    params?: GetAdminModulesParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Module[]>(
      {url: `/admin/modules`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminModulesQueryKey = (params?: GetAdminModulesParams,) => {
    return [
    `/admin/modules`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminModulesQueryOptions = <TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(params?: GetAdminModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminModulesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminModules>>> = ({ signal }) => getAdminModules(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminModules>>>
export type GetAdminModulesQueryError = unknown


export function useGetAdminModules<TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(
 params: undefined |  GetAdminModulesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminModules>>,
          TError,
          Awaited<ReturnType<typeof getAdminModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminModules<TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(
 params?: GetAdminModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminModules>>,
          TError,
          Awaited<ReturnType<typeof getAdminModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminModules<TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(
 params?: GetAdminModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminModules<TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(
 params?: GetAdminModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminModulesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminModulesId = (
    id: string,
    patchAdminModulesIdBody: PatchAdminModulesIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/modules/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminModulesIdBody
    },
      options);
    }
  


export const getPatchAdminModulesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext> => {

const mutationKey = ['patchAdminModulesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminModulesId>>, {id: string;data: PatchAdminModulesIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminModulesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminModulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminModulesId>>>
    export type PatchAdminModulesIdMutationBody = PatchAdminModulesIdBody
    export type PatchAdminModulesIdMutationError = unknown

    export const usePatchAdminModulesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminModulesId>>,
        TError,
        {id: string;data: PatchAdminModulesIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminModulesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminModulesId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/modules/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminModulesIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminModulesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminModulesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminModulesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminModulesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminModulesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminModulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminModulesId>>>
    
    export type DeleteAdminModulesIdMutationError = void

    export const useDeleteAdminModulesId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminModulesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminModulesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminModulesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminSubjects = (
    postAdminSubjectsBody: PostAdminSubjectsBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/subjects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminSubjectsBody, signal
    },
      options);
    }
  


export const getPostAdminSubjectsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext> => {

const mutationKey = ['postAdminSubjects'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminSubjects>>, {data: PostAdminSubjectsBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminSubjects(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminSubjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminSubjects>>>
    export type PostAdminSubjectsMutationBody = PostAdminSubjectsBody
    export type PostAdminSubjectsMutationError = unknown

    export const usePostAdminSubjects = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminSubjects>>,
        TError,
        {data: PostAdminSubjectsBody},
        TContext
      > => {

      const mutationOptions = getPostAdminSubjectsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminSubjects = (
    params?: GetAdminSubjectsParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Subject[]>(
      {url: `/admin/subjects`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminSubjectsQueryKey = (params?: GetAdminSubjectsParams,) => {
    return [
    `/admin/subjects`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminSubjectsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(params?: GetAdminSubjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSubjectsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSubjects>>> = ({ signal }) => getAdminSubjects(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminSubjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSubjects>>>
export type GetAdminSubjectsQueryError = unknown


export function useGetAdminSubjects<TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(
 params: undefined |  GetAdminSubjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSubjects>>,
          TError,
          Awaited<ReturnType<typeof getAdminSubjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminSubjects<TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(
 params?: GetAdminSubjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSubjects>>,
          TError,
          Awaited<ReturnType<typeof getAdminSubjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminSubjects<TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(
 params?: GetAdminSubjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminSubjects<TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(
 params?: GetAdminSubjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminSubjectsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminSubjectsId = (
    id: string,
    patchAdminSubjectsIdBody: PatchAdminSubjectsIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/subjects/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminSubjectsIdBody
    },
      options);
    }
  


export const getPatchAdminSubjectsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext> => {

const mutationKey = ['patchAdminSubjectsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminSubjectsId>>, {id: string;data: PatchAdminSubjectsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminSubjectsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminSubjectsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminSubjectsId>>>
    export type PatchAdminSubjectsIdMutationBody = PatchAdminSubjectsIdBody
    export type PatchAdminSubjectsIdMutationError = unknown

    export const usePatchAdminSubjectsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminSubjectsId>>,
        TError,
        {id: string;data: PatchAdminSubjectsIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminSubjectsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminSubjectsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/subjects/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminSubjectsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSubjectsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSubjectsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminSubjectsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminSubjectsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminSubjectsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminSubjectsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminSubjectsId>>>
    
    export type DeleteAdminSubjectsIdMutationError = void

    export const useDeleteAdminSubjectsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSubjectsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminSubjectsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminSubjectsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminQuestions = (
    params?: GetAdminQuestionsParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Question[]>(
      {url: `/admin/questions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminQuestionsQueryKey = (params?: GetAdminQuestionsParams,) => {
    return [
    `/admin/questions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminQuestionsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminQuestionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminQuestions>>> = ({ signal }) => getAdminQuestions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminQuestions>>>
export type GetAdminQuestionsQueryError = unknown


export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params: undefined |  GetAdminQuestionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminQuestions>>,
          TError,
          Awaited<ReturnType<typeof getAdminQuestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminQuestions>>,
          TError,
          Awaited<ReturnType<typeof getAdminQuestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminQuestionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminQuestionsBulkAssignStudyUnit = (
    patchAdminQuestionsBulkAssignStudyUnitBody: PatchAdminQuestionsBulkAssignStudyUnitBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/bulk-assign-study-unit`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminQuestionsBulkAssignStudyUnitBody
    },
      options);
    }
  


export const getPatchAdminQuestionsBulkAssignStudyUnitMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignStudyUnit>>, TError,{data: PatchAdminQuestionsBulkAssignStudyUnitBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignStudyUnit>>, TError,{data: PatchAdminQuestionsBulkAssignStudyUnitBody}, TContext> => {

const mutationKey = ['patchAdminQuestionsBulkAssignStudyUnit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignStudyUnit>>, {data: PatchAdminQuestionsBulkAssignStudyUnitBody}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminQuestionsBulkAssignStudyUnit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsBulkAssignStudyUnitMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignStudyUnit>>>
    export type PatchAdminQuestionsBulkAssignStudyUnitMutationBody = PatchAdminQuestionsBulkAssignStudyUnitBody
    export type PatchAdminQuestionsBulkAssignStudyUnitMutationError = unknown

    export const usePatchAdminQuestionsBulkAssignStudyUnit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignStudyUnit>>, TError,{data: PatchAdminQuestionsBulkAssignStudyUnitBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignStudyUnit>>,
        TError,
        {data: PatchAdminQuestionsBulkAssignStudyUnitBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsBulkAssignStudyUnitMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminQuestionsBulkAssignTelegramRange = (
    patchAdminQuestionsBulkAssignTelegramRangeBody: PatchAdminQuestionsBulkAssignTelegramRangeBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/bulk-assign-telegram-range`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminQuestionsBulkAssignTelegramRangeBody
    },
      options);
    }
  


export const getPatchAdminQuestionsBulkAssignTelegramRangeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignTelegramRange>>, TError,{data: PatchAdminQuestionsBulkAssignTelegramRangeBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignTelegramRange>>, TError,{data: PatchAdminQuestionsBulkAssignTelegramRangeBody}, TContext> => {

const mutationKey = ['patchAdminQuestionsBulkAssignTelegramRange'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignTelegramRange>>, {data: PatchAdminQuestionsBulkAssignTelegramRangeBody}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminQuestionsBulkAssignTelegramRange(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsBulkAssignTelegramRangeMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignTelegramRange>>>
    export type PatchAdminQuestionsBulkAssignTelegramRangeMutationBody = PatchAdminQuestionsBulkAssignTelegramRangeBody
    export type PatchAdminQuestionsBulkAssignTelegramRangeMutationError = unknown

    export const usePatchAdminQuestionsBulkAssignTelegramRange = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignTelegramRange>>, TError,{data: PatchAdminQuestionsBulkAssignTelegramRangeBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignTelegramRange>>,
        TError,
        {data: PatchAdminQuestionsBulkAssignTelegramRangeBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsBulkAssignTelegramRangeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminQuestionsBulkUnassignStudyUnit = (
    patchAdminQuestionsBulkUnassignStudyUnitBody: PatchAdminQuestionsBulkUnassignStudyUnitBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/bulk-unassign-study-unit`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminQuestionsBulkUnassignStudyUnitBody
    },
      options);
    }
  


export const getPatchAdminQuestionsBulkUnassignStudyUnitMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignStudyUnit>>, TError,{data: PatchAdminQuestionsBulkUnassignStudyUnitBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignStudyUnit>>, TError,{data: PatchAdminQuestionsBulkUnassignStudyUnitBody}, TContext> => {

const mutationKey = ['patchAdminQuestionsBulkUnassignStudyUnit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignStudyUnit>>, {data: PatchAdminQuestionsBulkUnassignStudyUnitBody}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminQuestionsBulkUnassignStudyUnit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsBulkUnassignStudyUnitMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignStudyUnit>>>
    export type PatchAdminQuestionsBulkUnassignStudyUnitMutationBody = PatchAdminQuestionsBulkUnassignStudyUnitBody
    export type PatchAdminQuestionsBulkUnassignStudyUnitMutationError = unknown

    export const usePatchAdminQuestionsBulkUnassignStudyUnit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignStudyUnit>>, TError,{data: PatchAdminQuestionsBulkUnassignStudyUnitBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignStudyUnit>>,
        TError,
        {data: PatchAdminQuestionsBulkUnassignStudyUnitBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsBulkUnassignStudyUnitMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminQuestionsBulkDelete = (
    postAdminQuestionsBulkDeleteBody: PostAdminQuestionsBulkDeleteBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<PostAdminQuestionsBulkDelete200>(
      {url: `/admin/questions/bulk-delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminQuestionsBulkDeleteBody, signal
    },
      options);
    }
  


export const getPostAdminQuestionsBulkDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminQuestionsBulkDelete>>, TError,{data: PostAdminQuestionsBulkDeleteBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminQuestionsBulkDelete>>, TError,{data: PostAdminQuestionsBulkDeleteBody}, TContext> => {

const mutationKey = ['postAdminQuestionsBulkDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminQuestionsBulkDelete>>, {data: PostAdminQuestionsBulkDeleteBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminQuestionsBulkDelete(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminQuestionsBulkDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminQuestionsBulkDelete>>>
    export type PostAdminQuestionsBulkDeleteMutationBody = PostAdminQuestionsBulkDeleteBody
    export type PostAdminQuestionsBulkDeleteMutationError = unknown

    export const usePostAdminQuestionsBulkDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminQuestionsBulkDelete>>, TError,{data: PostAdminQuestionsBulkDeleteBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminQuestionsBulkDelete>>,
        TError,
        {data: PostAdminQuestionsBulkDeleteBody},
        TContext
      > => {

      const mutationOptions = getPostAdminQuestionsBulkDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminQuestionsId = (
    id: string,
    question: Question,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: question
    },
      options);
    }
  


export const getPatchAdminQuestionsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext> => {

const mutationKey = ['patchAdminQuestionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsId>>, {id: string;data: Question}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminQuestionsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsId>>>
    export type PatchAdminQuestionsIdMutationBody = Question
    export type PatchAdminQuestionsIdMutationError = unknown

    export const usePatchAdminQuestionsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsId>>,
        TError,
        {id: string;data: Question},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminQuestionsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminQuestionsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminQuestionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminQuestionsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminQuestionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminQuestionsId>>>
    
    export type DeleteAdminQuestionsIdMutationError = unknown

    export const useDeleteAdminQuestionsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminQuestionsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminQuestionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminStudyUnits = (
    postAdminStudyUnitsBody: PostAdminStudyUnitsBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/study-units`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminStudyUnitsBody, signal
    },
      options);
    }
  


export const getPostAdminStudyUnitsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnits>>, TError,{data: PostAdminStudyUnitsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnits>>, TError,{data: PostAdminStudyUnitsBody}, TContext> => {

const mutationKey = ['postAdminStudyUnits'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminStudyUnits>>, {data: PostAdminStudyUnitsBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminStudyUnits(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminStudyUnitsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminStudyUnits>>>
    export type PostAdminStudyUnitsMutationBody = PostAdminStudyUnitsBody
    export type PostAdminStudyUnitsMutationError = unknown

    export const usePostAdminStudyUnits = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnits>>, TError,{data: PostAdminStudyUnitsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminStudyUnits>>,
        TError,
        {data: PostAdminStudyUnitsBody},
        TContext
      > => {

      const mutationOptions = getPostAdminStudyUnitsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminStudyUnits = (
    params?: GetAdminStudyUnitsParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<StudyUnit[]>(
      {url: `/admin/study-units`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminStudyUnitsQueryKey = (params?: GetAdminStudyUnitsParams,) => {
    return [
    `/admin/study-units`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminStudyUnitsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminStudyUnits>>, TError = unknown>(params?: GetAdminStudyUnitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStudyUnits>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminStudyUnitsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStudyUnits>>> = ({ signal }) => getAdminStudyUnits(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminStudyUnits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminStudyUnitsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminStudyUnits>>>
export type GetAdminStudyUnitsQueryError = unknown


export function useGetAdminStudyUnits<TData = Awaited<ReturnType<typeof getAdminStudyUnits>>, TError = unknown>(
 params: undefined |  GetAdminStudyUnitsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStudyUnits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminStudyUnits>>,
          TError,
          Awaited<ReturnType<typeof getAdminStudyUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminStudyUnits<TData = Awaited<ReturnType<typeof getAdminStudyUnits>>, TError = unknown>(
 params?: GetAdminStudyUnitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStudyUnits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminStudyUnits>>,
          TError,
          Awaited<ReturnType<typeof getAdminStudyUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminStudyUnits<TData = Awaited<ReturnType<typeof getAdminStudyUnits>>, TError = unknown>(
 params?: GetAdminStudyUnitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStudyUnits>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminStudyUnits<TData = Awaited<ReturnType<typeof getAdminStudyUnits>>, TError = unknown>(
 params?: GetAdminStudyUnitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStudyUnits>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminStudyUnitsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminStudyUnitsId = (
    id: string,
    patchAdminStudyUnitsIdBody: PatchAdminStudyUnitsIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/study-units/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminStudyUnitsIdBody
    },
      options);
    }
  


export const getPatchAdminStudyUnitsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminStudyUnitsId>>, TError,{id: string;data: PatchAdminStudyUnitsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminStudyUnitsId>>, TError,{id: string;data: PatchAdminStudyUnitsIdBody}, TContext> => {

const mutationKey = ['patchAdminStudyUnitsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminStudyUnitsId>>, {id: string;data: PatchAdminStudyUnitsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminStudyUnitsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminStudyUnitsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminStudyUnitsId>>>
    export type PatchAdminStudyUnitsIdMutationBody = PatchAdminStudyUnitsIdBody
    export type PatchAdminStudyUnitsIdMutationError = unknown

    export const usePatchAdminStudyUnitsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminStudyUnitsId>>, TError,{id: string;data: PatchAdminStudyUnitsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminStudyUnitsId>>,
        TError,
        {id: string;data: PatchAdminStudyUnitsIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminStudyUnitsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminStudyUnitsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/study-units/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminStudyUnitsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminStudyUnitsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminStudyUnitsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminStudyUnitsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminStudyUnitsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminStudyUnitsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminStudyUnitsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminStudyUnitsId>>>
    
    export type DeleteAdminStudyUnitsIdMutationError = void

    export const useDeleteAdminStudyUnitsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminStudyUnitsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminStudyUnitsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminStudyUnitsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminStudyUnitsIdVideos = (
    id: string,
    postAdminStudyUnitsIdVideosBody: PostAdminStudyUnitsIdVideosBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/study-units/${id}/videos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminStudyUnitsIdVideosBody, signal
    },
      options);
    }
  


export const getPostAdminStudyUnitsIdVideosMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnitsIdVideos>>, TError,{id: string;data: PostAdminStudyUnitsIdVideosBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnitsIdVideos>>, TError,{id: string;data: PostAdminStudyUnitsIdVideosBody}, TContext> => {

const mutationKey = ['postAdminStudyUnitsIdVideos'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminStudyUnitsIdVideos>>, {id: string;data: PostAdminStudyUnitsIdVideosBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postAdminStudyUnitsIdVideos(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminStudyUnitsIdVideosMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminStudyUnitsIdVideos>>>
    export type PostAdminStudyUnitsIdVideosMutationBody = PostAdminStudyUnitsIdVideosBody
    export type PostAdminStudyUnitsIdVideosMutationError = unknown

    export const usePostAdminStudyUnitsIdVideos = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnitsIdVideos>>, TError,{id: string;data: PostAdminStudyUnitsIdVideosBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminStudyUnitsIdVideos>>,
        TError,
        {id: string;data: PostAdminStudyUnitsIdVideosBody},
        TContext
      > => {

      const mutationOptions = getPostAdminStudyUnitsIdVideosMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminStudyUnitsIdFiles = (
    id: string,
    postAdminStudyUnitsIdFilesBody: PostAdminStudyUnitsIdFilesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/study-units/${id}/files`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminStudyUnitsIdFilesBody, signal
    },
      options);
    }
  


export const getPostAdminStudyUnitsIdFilesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnitsIdFiles>>, TError,{id: string;data: PostAdminStudyUnitsIdFilesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnitsIdFiles>>, TError,{id: string;data: PostAdminStudyUnitsIdFilesBody}, TContext> => {

const mutationKey = ['postAdminStudyUnitsIdFiles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminStudyUnitsIdFiles>>, {id: string;data: PostAdminStudyUnitsIdFilesBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postAdminStudyUnitsIdFiles(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminStudyUnitsIdFilesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminStudyUnitsIdFiles>>>
    export type PostAdminStudyUnitsIdFilesMutationBody = PostAdminStudyUnitsIdFilesBody
    export type PostAdminStudyUnitsIdFilesMutationError = unknown

    export const usePostAdminStudyUnitsIdFiles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminStudyUnitsIdFiles>>, TError,{id: string;data: PostAdminStudyUnitsIdFilesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminStudyUnitsIdFiles>>,
        TError,
        {id: string;data: PostAdminStudyUnitsIdFilesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminStudyUnitsIdFilesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get admin profile
 */
export const getAdminProfile = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<GetAdminProfile200>(
      {url: `/admin/profile`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminProfileQueryKey = () => {
    return [
    `/admin/profile`
    ] as const;
    }

    
export const getGetAdminProfileQueryOptions = <TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminProfile>>> = ({ signal }) => getAdminProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminProfile>>>
export type GetAdminProfileQueryError = unknown


export function useGetAdminProfile<TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminProfile>>,
          TError,
          Awaited<ReturnType<typeof getAdminProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminProfile<TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminProfile>>,
          TError,
          Awaited<ReturnType<typeof getAdminProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminProfile<TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get admin profile
 */

export function useGetAdminProfile<TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update admin profile
 */
export const patchAdminProfile = (
    patchAdminProfileBody: PatchAdminProfileBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminProfileBody
    },
      options);
    }
  


export const getPatchAdminProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminProfile>>, TError,{data: PatchAdminProfileBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminProfile>>, TError,{data: PatchAdminProfileBody}, TContext> => {

const mutationKey = ['patchAdminProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminProfile>>, {data: PatchAdminProfileBody}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminProfileMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminProfile>>>
    export type PatchAdminProfileMutationBody = PatchAdminProfileBody
    export type PatchAdminProfileMutationError = unknown

    /**
 * @summary Update admin profile
 */
export const usePatchAdminProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminProfile>>, TError,{data: PatchAdminProfileBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminProfile>>,
        TError,
        {data: PatchAdminProfileBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminUsers = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<GetAdminUsers200Item[]>(
      {url: `/admin/users`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminUsersQueryKey = () => {
    return [
    `/admin/users`
    ] as const;
    }

    
export const getGetAdminUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAdminUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminUsers>>> = ({ signal }) => getAdminUsers(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminUsers>>>
export type GetAdminUsersQueryError = unknown


export function useGetAdminUsers<TData = Awaited<ReturnType<typeof getAdminUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminUsers>>,
          TError,
          Awaited<ReturnType<typeof getAdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminUsers<TData = Awaited<ReturnType<typeof getAdminUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminUsers>>,
          TError,
          Awaited<ReturnType<typeof getAdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminUsers<TData = Awaited<ReturnType<typeof getAdminUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminUsers<TData = Awaited<ReturnType<typeof getAdminUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postAdminUsers = (
    postAdminUsersBody: PostAdminUsersBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminUsersBody, signal
    },
      options);
    }
  


export const getPostAdminUsersMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminUsers>>, TError,{data: PostAdminUsersBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminUsers>>, TError,{data: PostAdminUsersBody}, TContext> => {

const mutationKey = ['postAdminUsers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminUsers>>, {data: PostAdminUsersBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminUsers(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminUsers>>>
    export type PostAdminUsersMutationBody = PostAdminUsersBody
    export type PostAdminUsersMutationError = void

    export const usePostAdminUsers = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminUsers>>, TError,{data: PostAdminUsersBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminUsers>>,
        TError,
        {data: PostAdminUsersBody},
        TContext
      > => {

      const mutationOptions = getPostAdminUsersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminUsersId = (
    id: string,
    patchAdminUsersIdBody: PatchAdminUsersIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/users/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminUsersIdBody
    },
      options);
    }
  


export const getPatchAdminUsersIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminUsersId>>, TError,{id: string;data: PatchAdminUsersIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminUsersId>>, TError,{id: string;data: PatchAdminUsersIdBody}, TContext> => {

const mutationKey = ['patchAdminUsersId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminUsersId>>, {id: string;data: PatchAdminUsersIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminUsersId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminUsersId>>>
    export type PatchAdminUsersIdMutationBody = PatchAdminUsersIdBody
    export type PatchAdminUsersIdMutationError = void

    export const usePatchAdminUsersId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminUsersId>>, TError,{id: string;data: PatchAdminUsersIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminUsersId>>,
        TError,
        {id: string;data: PatchAdminUsersIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminUsersIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Permanently deletes a user and all their associated data (sessions, accounts, tokens, etc.)
 * @summary Delete a user account
 */
export const deleteAdminUsersId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/users/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminUsersIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminUsersId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminUsersId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminUsersId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminUsersId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminUsersId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminUsersId>>>
    
    export type DeleteAdminUsersIdMutationError = void

    /**
 * @summary Delete a user account
 */
export const useDeleteAdminUsersId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminUsersId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminUsersId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminUsersIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    