/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminLecturesParams,
  GetAdminModulesParams,
  GetAdminProfile200,
  GetAdminQuestionsParams,
  GetAdminSubjectsParams,
  GetAdminTermsParams,
  Grade,
  Lecture,
  Module,
  PatchAdminGradesIdBody,
  PatchAdminLecturesIdBody,
  PatchAdminModulesIdBody,
  PatchAdminProfileBody,
  PatchAdminQuestionsBulkAssignLectureBody,
  PatchAdminQuestionsBulkUnassignLectureBody,
  PatchAdminSubjectsIdBody,
  PatchAdminTermsIdBody,
  PostAdminGradesBody,
  PostAdminLecturesBody,
  PostAdminLecturesIdFilesBody,
  PostAdminLecturesIdVideosBody,
  PostAdminModulesBody,
  PostAdminSubjectsBody,
  PostAdminTermsBody,
  Question,
  Subject,
  Term
} from '.././model';

import { customAxios } from '.././mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const postAdminGrades = (
    postAdminGradesBody: PostAdminGradesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/grades`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminGradesBody, signal
    },
      options);
    }
  


export const getPostAdminGradesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext> => {

const mutationKey = ['postAdminGrades'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminGrades>>, {data: PostAdminGradesBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminGrades(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminGradesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminGrades>>>
    export type PostAdminGradesMutationBody = PostAdminGradesBody
    export type PostAdminGradesMutationError = unknown

    export const usePostAdminGrades = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminGrades>>, TError,{data: PostAdminGradesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminGrades>>,
        TError,
        {data: PostAdminGradesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminGradesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminGrades = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Grade[]>(
      {url: `/admin/grades`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminGradesQueryKey = () => {
    return [
    `/admin/grades`
    ] as const;
    }

    
export const getGetAdminGradesQueryOptions = <TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminGradesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminGrades>>> = ({ signal }) => getAdminGrades(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminGradesQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminGrades>>>
export type GetAdminGradesQueryError = unknown


export function useGetAdminGrades<TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminGrades>>,
          TError,
          Awaited<ReturnType<typeof getAdminGrades>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminGrades<TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminGrades>>,
          TError,
          Awaited<ReturnType<typeof getAdminGrades>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminGrades<TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminGrades<TData = Awaited<ReturnType<typeof getAdminGrades>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminGrades>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminGradesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminGradesId = (
    id: string,
    patchAdminGradesIdBody: PatchAdminGradesIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/grades/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminGradesIdBody
    },
      options);
    }
  


export const getPatchAdminGradesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext> => {

const mutationKey = ['patchAdminGradesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminGradesId>>, {id: string;data: PatchAdminGradesIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminGradesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminGradesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminGradesId>>>
    export type PatchAdminGradesIdMutationBody = PatchAdminGradesIdBody
    export type PatchAdminGradesIdMutationError = unknown

    export const usePatchAdminGradesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminGradesId>>, TError,{id: string;data: PatchAdminGradesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminGradesId>>,
        TError,
        {id: string;data: PatchAdminGradesIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminGradesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminGradesId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/grades/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminGradesIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminGradesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminGradesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminGradesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminGradesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminGradesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminGradesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminGradesId>>>
    
    export type DeleteAdminGradesIdMutationError = void

    export const useDeleteAdminGradesId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminGradesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminGradesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminGradesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminTerms = (
    postAdminTermsBody: PostAdminTermsBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/terms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminTermsBody, signal
    },
      options);
    }
  


export const getPostAdminTermsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext> => {

const mutationKey = ['postAdminTerms'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminTerms>>, {data: PostAdminTermsBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminTerms(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminTermsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminTerms>>>
    export type PostAdminTermsMutationBody = PostAdminTermsBody
    export type PostAdminTermsMutationError = unknown

    export const usePostAdminTerms = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminTerms>>, TError,{data: PostAdminTermsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminTerms>>,
        TError,
        {data: PostAdminTermsBody},
        TContext
      > => {

      const mutationOptions = getPostAdminTermsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminTerms = (
    params?: GetAdminTermsParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Term[]>(
      {url: `/admin/terms`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminTermsQueryKey = (params?: GetAdminTermsParams,) => {
    return [
    `/admin/terms`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminTermsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(params?: GetAdminTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminTermsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminTerms>>> = ({ signal }) => getAdminTerms(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminTermsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminTerms>>>
export type GetAdminTermsQueryError = unknown


export function useGetAdminTerms<TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(
 params: undefined |  GetAdminTermsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTerms>>,
          TError,
          Awaited<ReturnType<typeof getAdminTerms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminTerms<TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(
 params?: GetAdminTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTerms>>,
          TError,
          Awaited<ReturnType<typeof getAdminTerms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminTerms<TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(
 params?: GetAdminTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminTerms<TData = Awaited<ReturnType<typeof getAdminTerms>>, TError = unknown>(
 params?: GetAdminTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminTermsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminTermsId = (
    id: string,
    patchAdminTermsIdBody: PatchAdminTermsIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/terms/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminTermsIdBody
    },
      options);
    }
  


export const getPatchAdminTermsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext> => {

const mutationKey = ['patchAdminTermsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminTermsId>>, {id: string;data: PatchAdminTermsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminTermsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminTermsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminTermsId>>>
    export type PatchAdminTermsIdMutationBody = PatchAdminTermsIdBody
    export type PatchAdminTermsIdMutationError = unknown

    export const usePatchAdminTermsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminTermsId>>, TError,{id: string;data: PatchAdminTermsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminTermsId>>,
        TError,
        {id: string;data: PatchAdminTermsIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminTermsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminTermsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/terms/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminTermsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTermsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTermsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminTermsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminTermsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminTermsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminTermsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminTermsId>>>
    
    export type DeleteAdminTermsIdMutationError = void

    export const useDeleteAdminTermsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTermsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminTermsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminTermsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminModules = (
    postAdminModulesBody: PostAdminModulesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/modules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminModulesBody, signal
    },
      options);
    }
  


export const getPostAdminModulesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext> => {

const mutationKey = ['postAdminModules'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminModules>>, {data: PostAdminModulesBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminModules(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminModulesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminModules>>>
    export type PostAdminModulesMutationBody = PostAdminModulesBody
    export type PostAdminModulesMutationError = unknown

    export const usePostAdminModules = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminModules>>, TError,{data: PostAdminModulesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminModules>>,
        TError,
        {data: PostAdminModulesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminModulesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminModules = (
    params?: GetAdminModulesParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Module[]>(
      {url: `/admin/modules`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminModulesQueryKey = (params?: GetAdminModulesParams,) => {
    return [
    `/admin/modules`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminModulesQueryOptions = <TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(params?: GetAdminModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminModulesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminModules>>> = ({ signal }) => getAdminModules(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminModules>>>
export type GetAdminModulesQueryError = unknown


export function useGetAdminModules<TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(
 params: undefined |  GetAdminModulesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminModules>>,
          TError,
          Awaited<ReturnType<typeof getAdminModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminModules<TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(
 params?: GetAdminModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminModules>>,
          TError,
          Awaited<ReturnType<typeof getAdminModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminModules<TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(
 params?: GetAdminModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminModules<TData = Awaited<ReturnType<typeof getAdminModules>>, TError = unknown>(
 params?: GetAdminModulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminModules>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminModulesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminModulesId = (
    id: string,
    patchAdminModulesIdBody: PatchAdminModulesIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/modules/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminModulesIdBody
    },
      options);
    }
  


export const getPatchAdminModulesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext> => {

const mutationKey = ['patchAdminModulesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminModulesId>>, {id: string;data: PatchAdminModulesIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminModulesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminModulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminModulesId>>>
    export type PatchAdminModulesIdMutationBody = PatchAdminModulesIdBody
    export type PatchAdminModulesIdMutationError = unknown

    export const usePatchAdminModulesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminModulesId>>, TError,{id: string;data: PatchAdminModulesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminModulesId>>,
        TError,
        {id: string;data: PatchAdminModulesIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminModulesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminModulesId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/modules/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminModulesIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminModulesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminModulesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminModulesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminModulesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminModulesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminModulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminModulesId>>>
    
    export type DeleteAdminModulesIdMutationError = void

    export const useDeleteAdminModulesId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminModulesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminModulesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminModulesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminSubjects = (
    postAdminSubjectsBody: PostAdminSubjectsBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/subjects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminSubjectsBody, signal
    },
      options);
    }
  


export const getPostAdminSubjectsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext> => {

const mutationKey = ['postAdminSubjects'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminSubjects>>, {data: PostAdminSubjectsBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminSubjects(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminSubjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminSubjects>>>
    export type PostAdminSubjectsMutationBody = PostAdminSubjectsBody
    export type PostAdminSubjectsMutationError = unknown

    export const usePostAdminSubjects = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminSubjects>>, TError,{data: PostAdminSubjectsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminSubjects>>,
        TError,
        {data: PostAdminSubjectsBody},
        TContext
      > => {

      const mutationOptions = getPostAdminSubjectsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminSubjects = (
    params?: GetAdminSubjectsParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Subject[]>(
      {url: `/admin/subjects`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminSubjectsQueryKey = (params?: GetAdminSubjectsParams,) => {
    return [
    `/admin/subjects`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminSubjectsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(params?: GetAdminSubjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSubjectsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSubjects>>> = ({ signal }) => getAdminSubjects(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminSubjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSubjects>>>
export type GetAdminSubjectsQueryError = unknown


export function useGetAdminSubjects<TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(
 params: undefined |  GetAdminSubjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSubjects>>,
          TError,
          Awaited<ReturnType<typeof getAdminSubjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminSubjects<TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(
 params?: GetAdminSubjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSubjects>>,
          TError,
          Awaited<ReturnType<typeof getAdminSubjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminSubjects<TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(
 params?: GetAdminSubjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminSubjects<TData = Awaited<ReturnType<typeof getAdminSubjects>>, TError = unknown>(
 params?: GetAdminSubjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSubjects>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminSubjectsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminSubjectsId = (
    id: string,
    patchAdminSubjectsIdBody: PatchAdminSubjectsIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/subjects/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminSubjectsIdBody
    },
      options);
    }
  


export const getPatchAdminSubjectsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext> => {

const mutationKey = ['patchAdminSubjectsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminSubjectsId>>, {id: string;data: PatchAdminSubjectsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminSubjectsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminSubjectsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminSubjectsId>>>
    export type PatchAdminSubjectsIdMutationBody = PatchAdminSubjectsIdBody
    export type PatchAdminSubjectsIdMutationError = unknown

    export const usePatchAdminSubjectsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminSubjectsId>>, TError,{id: string;data: PatchAdminSubjectsIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminSubjectsId>>,
        TError,
        {id: string;data: PatchAdminSubjectsIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminSubjectsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminSubjectsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/subjects/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminSubjectsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSubjectsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSubjectsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminSubjectsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminSubjectsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminSubjectsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminSubjectsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminSubjectsId>>>
    
    export type DeleteAdminSubjectsIdMutationError = void

    export const useDeleteAdminSubjectsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSubjectsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminSubjectsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminSubjectsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminQuestions = (
    params?: GetAdminQuestionsParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Question[]>(
      {url: `/admin/questions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminQuestionsQueryKey = (params?: GetAdminQuestionsParams,) => {
    return [
    `/admin/questions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminQuestionsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminQuestionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminQuestions>>> = ({ signal }) => getAdminQuestions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminQuestions>>>
export type GetAdminQuestionsQueryError = unknown


export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params: undefined |  GetAdminQuestionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminQuestions>>,
          TError,
          Awaited<ReturnType<typeof getAdminQuestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminQuestions>>,
          TError,
          Awaited<ReturnType<typeof getAdminQuestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminQuestions<TData = Awaited<ReturnType<typeof getAdminQuestions>>, TError = unknown>(
 params?: GetAdminQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminQuestions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminQuestionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminQuestionsBulkAssignLecture = (
    patchAdminQuestionsBulkAssignLectureBody: PatchAdminQuestionsBulkAssignLectureBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/bulk-assign-lecture`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminQuestionsBulkAssignLectureBody
    },
      options);
    }

export const patchAdminQuestionsBulkUnassignLecture = (
    patchAdminQuestionsBulkUnassignLectureBody: PatchAdminQuestionsBulkUnassignLectureBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/bulk-unassign-lecture`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminQuestionsBulkUnassignLectureBody
    },
      options);
    }
  


export const getPatchAdminQuestionsBulkAssignLectureMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>, TError,{data: PatchAdminQuestionsBulkAssignLectureBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>, TError,{data: PatchAdminQuestionsBulkAssignLectureBody}, TContext> => {

const mutationKey = ['patchAdminQuestionsBulkAssignLecture'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>, {data: PatchAdminQuestionsBulkAssignLectureBody}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminQuestionsBulkAssignLecture(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsBulkAssignLectureMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>>
    export type PatchAdminQuestionsBulkAssignLectureMutationBody = PatchAdminQuestionsBulkAssignLectureBody
    export type PatchAdminQuestionsBulkAssignLectureMutationError = unknown

    export const usePatchAdminQuestionsBulkAssignLecture = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>, TError,{data: PatchAdminQuestionsBulkAssignLectureBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsBulkAssignLecture>>,
        TError,
        {data: PatchAdminQuestionsBulkAssignLectureBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsBulkAssignLectureMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }

export const getPatchAdminQuestionsBulkUnassignLectureMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignLecture>>, TError,{data: PatchAdminQuestionsBulkUnassignLectureBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignLecture>>, TError,{data: PatchAdminQuestionsBulkUnassignLectureBody}, TContext> => {

const mutationKey = ['patchAdminQuestionsBulkUnassignLecture'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};



      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignLecture>>, {data: PatchAdminQuestionsBulkUnassignLectureBody}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminQuestionsBulkUnassignLecture(data,requestOptions)
        }



  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsBulkUnassignLectureMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignLecture>>>
    export type PatchAdminQuestionsBulkUnassignLectureMutationBody = PatchAdminQuestionsBulkUnassignLectureBody
    export type PatchAdminQuestionsBulkUnassignLectureMutationError = unknown

    export const usePatchAdminQuestionsBulkUnassignLecture = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignLecture>>, TError,{data: PatchAdminQuestionsBulkUnassignLectureBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsBulkUnassignLecture>>,
        TError,
        {data: PatchAdminQuestionsBulkUnassignLectureBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsBulkUnassignLectureMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const patchAdminQuestionsId = (
    id: string,
    question: Question,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: question
    },
      options);
    }
  


export const getPatchAdminQuestionsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext> => {

const mutationKey = ['patchAdminQuestionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminQuestionsId>>, {id: string;data: Question}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminQuestionsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminQuestionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminQuestionsId>>>
    export type PatchAdminQuestionsIdMutationBody = Question
    export type PatchAdminQuestionsIdMutationError = unknown

    export const usePatchAdminQuestionsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminQuestionsId>>, TError,{id: string;data: Question}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminQuestionsId>>,
        TError,
        {id: string;data: Question},
        TContext
      > => {

      const mutationOptions = getPatchAdminQuestionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminQuestionsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/questions/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminQuestionsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminQuestionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminQuestionsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminQuestionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminQuestionsId>>>
    
    export type DeleteAdminQuestionsIdMutationError = unknown

    export const useDeleteAdminQuestionsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminQuestionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminQuestionsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminQuestionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminLectures = (
    postAdminLecturesBody: PostAdminLecturesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/lectures`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminLecturesBody, signal
    },
      options);
    }
  


export const getPostAdminLecturesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminLectures>>, TError,{data: PostAdminLecturesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminLectures>>, TError,{data: PostAdminLecturesBody}, TContext> => {

const mutationKey = ['postAdminLectures'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminLectures>>, {data: PostAdminLecturesBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminLectures(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminLecturesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminLectures>>>
    export type PostAdminLecturesMutationBody = PostAdminLecturesBody
    export type PostAdminLecturesMutationError = unknown

    export const usePostAdminLectures = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminLectures>>, TError,{data: PostAdminLecturesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminLectures>>,
        TError,
        {data: PostAdminLecturesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminLecturesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminLectures = (
    params?: GetAdminLecturesParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<Lecture[]>(
      {url: `/admin/lectures`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAdminLecturesQueryKey = (params?: GetAdminLecturesParams,) => {
    return [
    `/admin/lectures`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminLecturesQueryOptions = <TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(params?: GetAdminLecturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminLecturesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminLectures>>> = ({ signal }) => getAdminLectures(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminLecturesQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminLectures>>>
export type GetAdminLecturesQueryError = unknown


export function useGetAdminLectures<TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(
 params: undefined |  GetAdminLecturesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminLectures>>,
          TError,
          Awaited<ReturnType<typeof getAdminLectures>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminLectures<TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(
 params?: GetAdminLecturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminLectures>>,
          TError,
          Awaited<ReturnType<typeof getAdminLectures>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminLectures<TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(
 params?: GetAdminLecturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAdminLectures<TData = Awaited<ReturnType<typeof getAdminLectures>>, TError = unknown>(
 params?: GetAdminLecturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLectures>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminLecturesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const patchAdminLecturesId = (
    id: string,
    patchAdminLecturesIdBody: PatchAdminLecturesIdBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/lectures/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminLecturesIdBody
    },
      options);
    }
  


export const getPatchAdminLecturesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminLecturesId>>, TError,{id: string;data: PatchAdminLecturesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminLecturesId>>, TError,{id: string;data: PatchAdminLecturesIdBody}, TContext> => {

const mutationKey = ['patchAdminLecturesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminLecturesId>>, {id: string;data: PatchAdminLecturesIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminLecturesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminLecturesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminLecturesId>>>
    export type PatchAdminLecturesIdMutationBody = PatchAdminLecturesIdBody
    export type PatchAdminLecturesIdMutationError = unknown

    export const usePatchAdminLecturesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminLecturesId>>, TError,{id: string;data: PatchAdminLecturesIdBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminLecturesId>>,
        TError,
        {id: string;data: PatchAdminLecturesIdBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminLecturesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminLecturesId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/lectures/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminLecturesIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminLecturesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminLecturesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAdminLecturesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminLecturesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminLecturesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminLecturesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminLecturesId>>>
    
    export type DeleteAdminLecturesIdMutationError = void

    export const useDeleteAdminLecturesId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminLecturesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminLecturesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteAdminLecturesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminLecturesIdVideos = (
    id: string,
    postAdminLecturesIdVideosBody: PostAdminLecturesIdVideosBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/lectures/${id}/videos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminLecturesIdVideosBody, signal
    },
      options);
    }
  


export const getPostAdminLecturesIdVideosMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminLecturesIdVideos>>, TError,{id: string;data: PostAdminLecturesIdVideosBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminLecturesIdVideos>>, TError,{id: string;data: PostAdminLecturesIdVideosBody}, TContext> => {

const mutationKey = ['postAdminLecturesIdVideos'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminLecturesIdVideos>>, {id: string;data: PostAdminLecturesIdVideosBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postAdminLecturesIdVideos(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminLecturesIdVideosMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminLecturesIdVideos>>>
    export type PostAdminLecturesIdVideosMutationBody = PostAdminLecturesIdVideosBody
    export type PostAdminLecturesIdVideosMutationError = unknown

    export const usePostAdminLecturesIdVideos = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminLecturesIdVideos>>, TError,{id: string;data: PostAdminLecturesIdVideosBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminLecturesIdVideos>>,
        TError,
        {id: string;data: PostAdminLecturesIdVideosBody},
        TContext
      > => {

      const mutationOptions = getPostAdminLecturesIdVideosMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postAdminLecturesIdFiles = (
    id: string,
    postAdminLecturesIdFilesBody: PostAdminLecturesIdFilesBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/admin/lectures/${id}/files`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminLecturesIdFilesBody, signal
    },
      options);
    }
  


export const getPostAdminLecturesIdFilesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminLecturesIdFiles>>, TError,{id: string;data: PostAdminLecturesIdFilesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminLecturesIdFiles>>, TError,{id: string;data: PostAdminLecturesIdFilesBody}, TContext> => {

const mutationKey = ['postAdminLecturesIdFiles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminLecturesIdFiles>>, {id: string;data: PostAdminLecturesIdFilesBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postAdminLecturesIdFiles(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminLecturesIdFilesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminLecturesIdFiles>>>
    export type PostAdminLecturesIdFilesMutationBody = PostAdminLecturesIdFilesBody
    export type PostAdminLecturesIdFilesMutationError = unknown

    export const usePostAdminLecturesIdFiles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminLecturesIdFiles>>, TError,{id: string;data: PostAdminLecturesIdFilesBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminLecturesIdFiles>>,
        TError,
        {id: string;data: PostAdminLecturesIdFilesBody},
        TContext
      > => {

      const mutationOptions = getPostAdminLecturesIdFilesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get admin profile
 */
export const getAdminProfile = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<GetAdminProfile200>(
      {url: `/admin/profile`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminProfileQueryKey = () => {
    return [
    `/admin/profile`
    ] as const;
    }

    
export const getGetAdminProfileQueryOptions = <TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminProfile>>> = ({ signal }) => getAdminProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminProfile>>>
export type GetAdminProfileQueryError = unknown


export function useGetAdminProfile<TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminProfile>>,
          TError,
          Awaited<ReturnType<typeof getAdminProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminProfile<TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminProfile>>,
          TError,
          Awaited<ReturnType<typeof getAdminProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminProfile<TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get admin profile
 */

export function useGetAdminProfile<TData = Awaited<ReturnType<typeof getAdminProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update admin profile
 */
export const patchAdminProfile = (
    patchAdminProfileBody: PatchAdminProfileBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/admin/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAdminProfileBody
    },
      options);
    }
  


export const getPatchAdminProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminProfile>>, TError,{data: PatchAdminProfileBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminProfile>>, TError,{data: PatchAdminProfileBody}, TContext> => {

const mutationKey = ['patchAdminProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminProfile>>, {data: PatchAdminProfileBody}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminProfileMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminProfile>>>
    export type PatchAdminProfileMutationBody = PatchAdminProfileBody
    export type PatchAdminProfileMutationError = unknown

    /**
 * @summary Update admin profile
 */
export const usePatchAdminProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminProfile>>, TError,{data: PatchAdminProfileBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminProfile>>,
        TError,
        {data: PatchAdminProfileBody},
        TContext
      > => {

      const mutationOptions = getPatchAdminProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    