/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetContentSync200,
  GetContentSyncParams,
  LectureVideo,
  PostContentVideoProgressBody,
  StructuredGrade,
  StudyUnitDetails,
  VideoProgress
} from '.././model';

import { customAxios } from '.././mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Sync content for offline use
 */
export const getContentSync = (
    params?: GetContentSyncParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<GetContentSync200>(
      {url: `/content/sync`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetContentSyncQueryKey = (params?: GetContentSyncParams,) => {
    return [
    `/content/sync`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetContentSyncQueryOptions = <TData = Awaited<ReturnType<typeof getContentSync>>, TError = unknown>(params?: GetContentSyncParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentSync>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContentSyncQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContentSync>>> = ({ signal }) => getContentSync(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContentSync>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetContentSyncQueryResult = NonNullable<Awaited<ReturnType<typeof getContentSync>>>
export type GetContentSyncQueryError = unknown


export function useGetContentSync<TData = Awaited<ReturnType<typeof getContentSync>>, TError = unknown>(
 params: undefined |  GetContentSyncParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentSync>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentSync>>,
          TError,
          Awaited<ReturnType<typeof getContentSync>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetContentSync<TData = Awaited<ReturnType<typeof getContentSync>>, TError = unknown>(
 params?: GetContentSyncParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentSync>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentSync>>,
          TError,
          Awaited<ReturnType<typeof getContentSync>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetContentSync<TData = Awaited<ReturnType<typeof getContentSync>>, TError = unknown>(
 params?: GetContentSyncParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentSync>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Sync content for offline use
 */

export function useGetContentSync<TData = Awaited<ReturnType<typeof getContentSync>>, TError = unknown>(
 params?: GetContentSyncParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentSync>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetContentSyncQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get complete nested content hierarchy
 */
export const getContentHierarchy = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<StructuredGrade[]>(
      {url: `/content/hierarchy`, method: 'GET', signal
    },
      options);
    }
  



export const getGetContentHierarchyQueryKey = () => {
    return [
    `/content/hierarchy`
    ] as const;
    }

    
export const getGetContentHierarchyQueryOptions = <TData = Awaited<ReturnType<typeof getContentHierarchy>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentHierarchy>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContentHierarchyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContentHierarchy>>> = ({ signal }) => getContentHierarchy(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContentHierarchy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetContentHierarchyQueryResult = NonNullable<Awaited<ReturnType<typeof getContentHierarchy>>>
export type GetContentHierarchyQueryError = unknown


export function useGetContentHierarchy<TData = Awaited<ReturnType<typeof getContentHierarchy>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentHierarchy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentHierarchy>>,
          TError,
          Awaited<ReturnType<typeof getContentHierarchy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetContentHierarchy<TData = Awaited<ReturnType<typeof getContentHierarchy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentHierarchy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentHierarchy>>,
          TError,
          Awaited<ReturnType<typeof getContentHierarchy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetContentHierarchy<TData = Awaited<ReturnType<typeof getContentHierarchy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentHierarchy>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get complete nested content hierarchy
 */

export function useGetContentHierarchy<TData = Awaited<ReturnType<typeof getContentHierarchy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentHierarchy>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetContentHierarchyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get study unit details with videos, files, and questions
 */
export const getContentStudyUnitsId = (
    id: string,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<StudyUnitDetails>(
      {url: `/content/study-units/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetContentStudyUnitsIdQueryKey = (id?: string,) => {
    return [
    `/content/study-units/${id}`
    ] as const;
    }

    
export const getGetContentStudyUnitsIdQueryOptions = <TData = Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContentStudyUnitsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContentStudyUnitsId>>> = ({ signal }) => getContentStudyUnitsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetContentStudyUnitsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getContentStudyUnitsId>>>
export type GetContentStudyUnitsIdQueryError = void


export function useGetContentStudyUnitsId<TData = Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentStudyUnitsId>>,
          TError,
          Awaited<ReturnType<typeof getContentStudyUnitsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetContentStudyUnitsId<TData = Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentStudyUnitsId>>,
          TError,
          Awaited<ReturnType<typeof getContentStudyUnitsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetContentStudyUnitsId<TData = Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get study unit details with videos, files, and questions
 */

export function useGetContentStudyUnitsId<TData = Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsId>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetContentStudyUnitsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get videos for a study unit
 */
export const getContentStudyUnitsIdVideos = (
    id: string,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<LectureVideo[]>(
      {url: `/content/study-units/${id}/videos`, method: 'GET', signal
    },
      options);
    }
  



export const getGetContentStudyUnitsIdVideosQueryKey = (id?: string,) => {
    return [
    `/content/study-units/${id}/videos`
    ] as const;
    }

    
export const getGetContentStudyUnitsIdVideosQueryOptions = <TData = Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContentStudyUnitsIdVideosQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>> = ({ signal }) => getContentStudyUnitsIdVideos(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetContentStudyUnitsIdVideosQueryResult = NonNullable<Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>>
export type GetContentStudyUnitsIdVideosQueryError = unknown


export function useGetContentStudyUnitsIdVideos<TData = Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>,
          TError,
          Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetContentStudyUnitsIdVideos<TData = Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>,
          TError,
          Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetContentStudyUnitsIdVideos<TData = Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get videos for a study unit
 */

export function useGetContentStudyUnitsIdVideos<TData = Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContentStudyUnitsIdVideos>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetContentStudyUnitsIdVideosQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update video watch progress
 */
export const postContentVideoProgress = (
    postContentVideoProgressBody: PostContentVideoProgressBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<VideoProgress>(
      {url: `/content/video-progress`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postContentVideoProgressBody, signal
    },
      options);
    }
  


export const getPostContentVideoProgressMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postContentVideoProgress>>, TError,{data: PostContentVideoProgressBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postContentVideoProgress>>, TError,{data: PostContentVideoProgressBody}, TContext> => {

const mutationKey = ['postContentVideoProgress'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postContentVideoProgress>>, {data: PostContentVideoProgressBody}> = (props) => {
          const {data} = props ?? {};

          return  postContentVideoProgress(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostContentVideoProgressMutationResult = NonNullable<Awaited<ReturnType<typeof postContentVideoProgress>>>
    export type PostContentVideoProgressMutationBody = PostContentVideoProgressBody
    export type PostContentVideoProgressMutationError = unknown

    /**
 * @summary Update video watch progress
 */
export const usePostContentVideoProgress = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postContentVideoProgress>>, TError,{data: PostContentVideoProgressBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postContentVideoProgress>>,
        TError,
        {data: PostContentVideoProgressBody},
        TContext
      > => {

      const mutationOptions = getPostContentVideoProgressMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    