import { Activity, Bell, BookOpen, ChevronDown, ClipboardList, FileText, LayoutDashboard, Menu, Search, Settings, Users } from 'lucide-react';
import type { ReactNode } from 'react';
import type { Navigate, Page } from './types';

const nav = [['dashboard', 'Dashboard', LayoutDashboard], ['grades', 'Grades', ClipboardList], ['terms', 'Terms', FileText], ['modules', 'Modules', BookOpen], ['subjects', 'Subjects', Activity], ['lectures', 'Lectures', FileText], ['questions', 'Questions', ClipboardList], ['users', 'Users', Users]] as const;

export function DashboardLayout({ page, navigate, notify, children }: { page: Page; navigate: Navigate; notify: (message: string) => void; children: ReactNode }) {
  return <div className="min-h-screen bg-slate-50 text-slate-900"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col bg-[#006d68] px-4 py-5 text-white shadow-xl lg:flex"><Brand /><Nav page={page} navigate={navigate} /><SidebarFooter page={page} navigate={navigate} notify={notify} /></aside><main className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-white/95 px-4 backdrop-blur sm:px-8"><button className="rounded-md p-2 hover:bg-slate-100 lg:hidden" onClick={() => notify('Open the desktop sidebar to navigate')}><Menu size={20} /></button><div className="hidden items-center gap-2 text-sm sm:flex"><span className="text-slate-400">Workspace</span><span>/</span><strong>{page[0].toUpperCase() + page.slice(1)}</strong></div><div className="ml-auto flex items-center gap-3"><button className="hidden h-9 w-72 items-center gap-2 rounded-md border bg-slate-50 px-3 text-left text-xs text-slate-400 md:flex" onClick={() => notify('Global search opened')}><Search size={15} />Search content...</button><button className="rounded-md p-2 text-slate-600 hover:bg-slate-100" onClick={() => notify('No new notifications')}><Bell size={18} /></button><button className="flex items-center gap-2 border-l pl-3" onClick={() => notify('Profile menu opened')}><span className="grid size-8 place-items-center rounded-full bg-teal-100 text-xs font-bold text-teal-800">AD</span><span className="hidden text-left sm:block"><b className="block text-xs">Admin</b><small className="text-slate-400">Content manager</small></span><ChevronDown size={14} /></button></div></header><div className="mx-auto max-w-[1500px] p-4 sm:p-8">{children}</div></main></div>;
}

function Brand() { return <div className="mb-8 flex items-center gap-3 px-2"><div className="grid size-10 place-items-center rounded-xl bg-white text-xl font-bold text-[#006d68]">✚</div><div><p className="text-lg font-bold leading-none">MedEd <span className="font-normal">Curator</span></p><p className="mt-1 text-[10px] text-teal-100">Medical content management</p></div></div>; }
function Nav({ page, navigate }: { page: Page; navigate: Navigate }) { return <><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-teal-200">Workspace</p><nav className="space-y-1">{nav.map(([key, label, Icon]) => <button key={key} onClick={() => navigate(key)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${page === key ? 'bg-white/15 text-white' : 'text-teal-50/75 hover:bg-white/10 hover:text-white'}`}><Icon size={17} />{label}</button>)}</nav></>; }
function SidebarFooter({ page, navigate, notify }: { page: Page; navigate: Navigate; notify: (message: string) => void }) { return <div className="mt-auto space-y-4"><button onClick={() => navigate('settings')} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${page === 'settings' ? 'bg-white/15' : 'text-teal-50/75 hover:bg-white/10'}`}><Settings size={17} />Settings</button><button className="w-full rounded-xl border border-white/15 bg-white/10 p-3 text-left hover:bg-white/15" onClick={() => notify('Documentation is coming soon')}><p className="text-xs font-semibold">Need help?</p><p className="mt-1 text-[11px] text-teal-100">View documentation</p></button><p className="px-2 text-[10px] text-teal-200">MedEd Curator · v1.0.0</p></div>; }
