import { BookOpen, Check, ClipboardList, Plus, Upload } from 'lucide-react';
import { useGetAdminLectures, useGetAdminQuestions } from '@manhaj/api-client/src/admin/admin';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import type { Navigate } from './types';
import { Heading } from './Heading';

export function DashboardPage({ navigate }: { navigate: Navigate }) {
  const questions = useGetAdminQuestions({ lectureId: 'null' }); const lectures = useGetAdminLectures(); const unclassified = questions.data?.data.length || 0; const lectureCount = lectures.data?.data.length || 0; const stats = [['Unclassified Questions', unclassified, ClipboardList, 'questions'], ['Pending Lecture Uploads', '—', Upload, 'lectures'], ['Lectures', lectureCount, BookOpen, 'lectures'], ['Classified Questions', '—', Check, 'questions']] as const;
  return <><Heading eyebrow="Live workspace" title="Good morning, Admin" description="Overview loaded from the Neon-backed admin API." action={<Button onClick={() => navigate('questions')}><Plus size={16} />Manage content</Button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, Icon, target]) => <button key={label} onClick={() => navigate(target)} className="rounded-lg border bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className="grid size-10 place-items-center rounded-lg bg-teal-50 text-teal-700"><Icon size={20} /></span><p className="mt-4 text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-400">Live API value</p></button>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Unclassified questions</CardTitle><CardDescription>Questions without a lecture</CardDescription></CardHeader><CardContent>{questions.isLoading ? <p className="text-sm text-slate-500">Loading...</p> : questions.isError ? <p className="text-sm text-red-600">Unable to load questions.</p> : <p className="text-4xl font-bold text-teal-700">{unclassified}</p>}</CardContent></Card><Card><CardHeader><CardTitle>Lectures</CardTitle><CardDescription>Available through the admin API</CardDescription></CardHeader><CardContent>{lectures.isLoading ? <p className="text-sm text-slate-500">Loading...</p> : lectures.isError ? <p className="text-sm text-red-600">Unable to load lectures.</p> : <p className="text-4xl font-bold text-teal-700">{lectureCount}</p>}</CardContent></Card></div></>;
}
