/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetStudentGradesWithTerms200Item,
  GetStudentProfile200,
  PatchStudentProfileBody,
  PostStudentAttemptsSync200,
  PostStudentAttemptsSyncBody,
  PostStudentDevicesRegisterBody,
  PostStudentFlagsBody
} from '.././model';

import { customAxios } from '.././mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get student profile
 */
export const getStudentProfile = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<GetStudentProfile200>(
      {url: `/student/profile`, method: 'GET', signal
    },
      options);
    }
  



export const getGetStudentProfileQueryKey = () => {
    return [
    `/student/profile`
    ] as const;
    }

    
export const getGetStudentProfileQueryOptions = <TData = Awaited<ReturnType<typeof getStudentProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentProfile>>> = ({ signal }) => getStudentProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetStudentProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentProfile>>>
export type GetStudentProfileQueryError = unknown


export function useGetStudentProfile<TData = Awaited<ReturnType<typeof getStudentProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentProfile>>,
          TError,
          Awaited<ReturnType<typeof getStudentProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetStudentProfile<TData = Awaited<ReturnType<typeof getStudentProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentProfile>>,
          TError,
          Awaited<ReturnType<typeof getStudentProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetStudentProfile<TData = Awaited<ReturnType<typeof getStudentProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get student profile
 */

export function useGetStudentProfile<TData = Awaited<ReturnType<typeof getStudentProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentProfile>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetStudentProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update student profile
 */
export const patchStudentProfile = (
    patchStudentProfileBody: PatchStudentProfileBody,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/student/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchStudentProfileBody
    },
      options);
    }
  


export const getPatchStudentProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchStudentProfile>>, TError,{data: PatchStudentProfileBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchStudentProfile>>, TError,{data: PatchStudentProfileBody}, TContext> => {

const mutationKey = ['patchStudentProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchStudentProfile>>, {data: PatchStudentProfileBody}> = (props) => {
          const {data} = props ?? {};

          return  patchStudentProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchStudentProfileMutationResult = NonNullable<Awaited<ReturnType<typeof patchStudentProfile>>>
    export type PatchStudentProfileMutationBody = PatchStudentProfileBody
    export type PatchStudentProfileMutationError = unknown

    /**
 * @summary Update student profile
 */
export const usePatchStudentProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchStudentProfile>>, TError,{data: PatchStudentProfileBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchStudentProfile>>,
        TError,
        {data: PatchStudentProfileBody},
        TContext
      > => {

      const mutationOptions = getPatchStudentProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get grades with their terms
 */
export const getStudentGradesWithTerms = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<GetStudentGradesWithTerms200Item[]>(
      {url: `/student/grades-with-terms`, method: 'GET', signal
    },
      options);
    }
  



export const getGetStudentGradesWithTermsQueryKey = () => {
    return [
    `/student/grades-with-terms`
    ] as const;
    }

    
export const getGetStudentGradesWithTermsQueryOptions = <TData = Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentGradesWithTermsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentGradesWithTerms>>> = ({ signal }) => getStudentGradesWithTerms(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetStudentGradesWithTermsQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentGradesWithTerms>>>
export type GetStudentGradesWithTermsQueryError = unknown


export function useGetStudentGradesWithTerms<TData = Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentGradesWithTerms>>,
          TError,
          Awaited<ReturnType<typeof getStudentGradesWithTerms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetStudentGradesWithTerms<TData = Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentGradesWithTerms>>,
          TError,
          Awaited<ReturnType<typeof getStudentGradesWithTerms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetStudentGradesWithTerms<TData = Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get grades with their terms
 */

export function useGetStudentGradesWithTerms<TData = Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentGradesWithTerms>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetStudentGradesWithTermsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Sync student attempts to server
 */
export const postStudentAttemptsSync = (
    postStudentAttemptsSyncBody: PostStudentAttemptsSyncBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<PostStudentAttemptsSync200>(
      {url: `/student/attempts/sync`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postStudentAttemptsSyncBody, signal
    },
      options);
    }
  


export const getPostStudentAttemptsSyncMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStudentAttemptsSync>>, TError,{data: PostStudentAttemptsSyncBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postStudentAttemptsSync>>, TError,{data: PostStudentAttemptsSyncBody}, TContext> => {

const mutationKey = ['postStudentAttemptsSync'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postStudentAttemptsSync>>, {data: PostStudentAttemptsSyncBody}> = (props) => {
          const {data} = props ?? {};

          return  postStudentAttemptsSync(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostStudentAttemptsSyncMutationResult = NonNullable<Awaited<ReturnType<typeof postStudentAttemptsSync>>>
    export type PostStudentAttemptsSyncMutationBody = PostStudentAttemptsSyncBody
    export type PostStudentAttemptsSyncMutationError = unknown

    /**
 * @summary Sync student attempts to server
 */
export const usePostStudentAttemptsSync = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStudentAttemptsSync>>, TError,{data: PostStudentAttemptsSyncBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postStudentAttemptsSync>>,
        TError,
        {data: PostStudentAttemptsSyncBody},
        TContext
      > => {

      const mutationOptions = getPostStudentAttemptsSyncMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Flag a question
 */
export const postStudentFlags = (
    postStudentFlagsBody: PostStudentFlagsBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/student/flags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postStudentFlagsBody, signal
    },
      options);
    }
  


export const getPostStudentFlagsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStudentFlags>>, TError,{data: PostStudentFlagsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postStudentFlags>>, TError,{data: PostStudentFlagsBody}, TContext> => {

const mutationKey = ['postStudentFlags'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postStudentFlags>>, {data: PostStudentFlagsBody}> = (props) => {
          const {data} = props ?? {};

          return  postStudentFlags(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostStudentFlagsMutationResult = NonNullable<Awaited<ReturnType<typeof postStudentFlags>>>
    export type PostStudentFlagsMutationBody = PostStudentFlagsBody
    export type PostStudentFlagsMutationError = unknown

    /**
 * @summary Flag a question
 */
export const usePostStudentFlags = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStudentFlags>>, TError,{data: PostStudentFlagsBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postStudentFlags>>,
        TError,
        {data: PostStudentFlagsBody},
        TContext
      > => {

      const mutationOptions = getPostStudentFlagsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove flag from question
 */
export const deleteStudentFlagsQuestionId = (
    questionId: string,
 options?: SecondParameter<typeof customAxios>,) => {
      
      
      return customAxios<void>(
      {url: `/student/flags/${questionId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteStudentFlagsQuestionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStudentFlagsQuestionId>>, TError,{questionId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStudentFlagsQuestionId>>, TError,{questionId: string}, TContext> => {

const mutationKey = ['deleteStudentFlagsQuestionId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStudentFlagsQuestionId>>, {questionId: string}> = (props) => {
          const {questionId} = props ?? {};

          return  deleteStudentFlagsQuestionId(questionId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStudentFlagsQuestionIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStudentFlagsQuestionId>>>
    
    export type DeleteStudentFlagsQuestionIdMutationError = unknown

    /**
 * @summary Remove flag from question
 */
export const useDeleteStudentFlagsQuestionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStudentFlagsQuestionId>>, TError,{questionId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStudentFlagsQuestionId>>,
        TError,
        {questionId: string},
        TContext
      > => {

      const mutationOptions = getDeleteStudentFlagsQuestionIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Register an Expo push token
 */
export const postStudentDevicesRegister = (
    postStudentDevicesRegisterBody: PostStudentDevicesRegisterBody,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<void>(
      {url: `/student/devices/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postStudentDevicesRegisterBody, signal
    },
      options);
    }
  


export const getPostStudentDevicesRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStudentDevicesRegister>>, TError,{data: PostStudentDevicesRegisterBody}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postStudentDevicesRegister>>, TError,{data: PostStudentDevicesRegisterBody}, TContext> => {

const mutationKey = ['postStudentDevicesRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postStudentDevicesRegister>>, {data: PostStudentDevicesRegisterBody}> = (props) => {
          const {data} = props ?? {};

          return  postStudentDevicesRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostStudentDevicesRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postStudentDevicesRegister>>>
    export type PostStudentDevicesRegisterMutationBody = PostStudentDevicesRegisterBody
    export type PostStudentDevicesRegisterMutationError = unknown

    /**
 * @summary Register an Expo push token
 */
export const usePostStudentDevicesRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStudentDevicesRegister>>, TError,{data: PostStudentDevicesRegisterBody}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postStudentDevicesRegister>>,
        TError,
        {data: PostStudentDevicesRegisterBody},
        TContext
      > => {

      const mutationOptions = getPostStudentDevicesRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    