/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Grade {
  id?: string;
  name?: string;
  description?: string;
}

export interface Term {
  id?: string;
  gradeId?: string;
  name?: string;
  description?: string;
}

export interface Module {
  id?: string;
  termId?: string;
  name?: string;
  description?: string;
}

export interface Subject {
  id?: string;
  moduleId?: string;
  name?: string;
}

export interface Lecture {
  id?: string;
  subjectId?: string;
  name?: string;
  description?: string;
}

export type QuestionSource = typeof QuestionSource[keyof typeof QuestionSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionSource = {
  telegram_auto: 'telegram_auto',
  admin_manual: 'admin_manual',
} as const;

export interface Question {
  id?: string;
  /** @nullable */
  lectureId?: string | null;
  /** @nullable */
  createdBy?: string | null;
  questionText?: string;
  explanation?: string;
  source?: QuestionSource;
}

export interface Choice {
  id?: string;
  questionId?: string;
  choiceText?: string;
  isCorrect?: boolean;
}

export interface LectureVideo {
  id?: string;
  lectureId?: string;
  sourceName?: string;
  url?: string;
  duration?: number;
}

export interface LectureFile {
  id?: string;
  lectureId?: string;
  sourceName?: string;
  fileUrl?: string;
  fileType?: string;
}

export interface VideoProgress {
  id?: string;
  userId?: string;
  lectureVideoId?: string;
  positionSeconds?: number;
  updatedAt?: string;
}

export type UserAuthProvider = typeof UserAuthProvider[keyof typeof UserAuthProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserAuthProvider = {
  google: 'google',
  credentials: 'credentials',
} as const;

export type UserRole = typeof UserRole[keyof typeof UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  student: 'student',
  admin: 'admin',
} as const;

export interface User {
  id?: string;
  name?: string;
  email?: string;
  authProvider?: UserAuthProvider;
  role?: UserRole;
  /** @nullable */
  termId?: string | null;
}

export interface AuthResponse {
  accessToken?: string;
  refreshToken?: string;
  user?: User;
}

export interface Attempt {
  id?: string;
  userId?: string;
  questionId?: string;
  choiceId?: string;
  isCorrect?: boolean;
}

export interface Flag {
  id?: string;
  userId?: string;
  questionId?: string;
}

export type PostStudentDevicesRegisterBodyPlatform = typeof PostStudentDevicesRegisterBodyPlatform[keyof typeof PostStudentDevicesRegisterBodyPlatform];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostStudentDevicesRegisterBodyPlatform = {
  ios: 'ios',
  android: 'android',
} as const;

export type PostStudentDevicesRegisterBody = {
  pushToken: string;
  platform: PostStudentDevicesRegisterBodyPlatform;
};

export type GetContentSyncParams = {
/**
 * Cursor for delta sync (ISO timestamp)
 */
since?: string;
};

export type GetContentSync200 = {
  grades?: Grade[];
  terms?: Term[];
  modules?: Module[];
  subjects?: Subject[];
  lectures?: Lecture[];
  questions?: Question[];
  choices?: Choice[];
  lectureVideos?: LectureVideo[];
  lectureFiles?: LectureFile[];
  nextCursor?: string;
};

export type PostContentVideoProgressBody = {
  lectureVideoId: string;
  positionSeconds: number;
};

export type PostAuthGoogleBody = {
  idToken?: string;
};

export type PostAuthRegisterBody = {
  name?: string;
  email?: string;
  password?: string;
};

export type PostAuthLoginBody = {
  email?: string;
  password?: string;
};

export type PostAuthRefreshBody = {
  token?: string;
};

export type PostAuthLogoutBody = {
  token?: string;
};

/**
 * @summary Register an Expo push token
 */
export const postStudentDevicesRegister = <TData = AxiosResponse<void>>(
    postStudentDevicesRegisterBody: PostStudentDevicesRegisterBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/student/devices/register`,
      postStudentDevicesRegisterBody,options
    );
  }

/**
 * @summary Sync content for offline use
 */
export const getContentSync = <TData = AxiosResponse<GetContentSync200>>(
    params?: GetContentSyncParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/content/sync`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get videos for a lecture
 */
export const getContentLecturesIdVideos = <TData = AxiosResponse<LectureVideo[]>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/content/lectures/${id}/videos`,options
    );
  }

/**
 * @summary Update video watch progress
 */
export const postContentVideoProgress = <TData = AxiosResponse<VideoProgress>>(
    postContentVideoProgressBody: PostContentVideoProgressBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/content/video-progress`,
      postContentVideoProgressBody,options
    );
  }

/**
 * @summary Authenticate with Google
 */
export const postAuthGoogle = <TData = AxiosResponse<void>>(
    postAuthGoogleBody: PostAuthGoogleBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/google`,
      postAuthGoogleBody,options
    );
  }

/**
 * @summary Register a new user
 */
export const postAuthRegister = <TData = AxiosResponse<void>>(
    postAuthRegisterBody: PostAuthRegisterBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/register`,
      postAuthRegisterBody,options
    );
  }

/**
 * @summary Login with email and password
 */
export const postAuthLogin = <TData = AxiosResponse<void>>(
    postAuthLoginBody: PostAuthLoginBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      postAuthLoginBody,options
    );
  }

/**
 * @summary Refresh access token
 */
export const postAuthRefresh = <TData = AxiosResponse<void>>(
    postAuthRefreshBody: PostAuthRefreshBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/refresh`,
      postAuthRefreshBody,options
    );
  }

/**
 * @summary Logout user
 */
export const postAuthLogout = <TData = AxiosResponse<void>>(
    postAuthLogoutBody: PostAuthLogoutBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/logout`,
      postAuthLogoutBody,options
    );
  }

export type PostStudentDevicesRegisterResult = AxiosResponse<void>
export type GetContentSyncResult = AxiosResponse<GetContentSync200>
export type GetContentLecturesIdVideosResult = AxiosResponse<LectureVideo[]>
export type PostContentVideoProgressResult = AxiosResponse<VideoProgress>
export type PostAuthGoogleResult = AxiosResponse<void>
export type PostAuthRegisterResult = AxiosResponse<void>
export type PostAuthLoginResult = AxiosResponse<void>
export type PostAuthRefreshResult = AxiosResponse<void>
export type PostAuthLogoutResult = AxiosResponse<void>
