/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export interface Attempt {
  id?: string;
  userId?: string;
  questionId?: string;
  choiceId?: string;
  isCorrect?: boolean;
  createdAt?: string;
}
