/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminStudyUnitsType } from './getAdminStudyUnitsType';

export type GetAdminStudyUnitsParams = {
subjectId?: string;
type?: GetAdminStudyUnitsType;
};
