/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminUsers200Item = {
  id?: string;
  name?: string;
  email?: string;
  role?: string;
  termId?: string;
  termName?: string;
  gradeId?: string;
  gradeName?: string;
  createdAt?: string;
  updatedAt?: string;
};
