/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { Grade } from './grade';
import type { Term } from './term';
import type { Module } from './module';
import type { Subject } from './subject';
import type { Lecture } from './lecture';
import type { Question } from './question';
import type { Choice } from './choice';
import type { QuestionSourceTag } from './questionSourceTag';
import type { LectureVideo } from './lectureVideo';
import type { LectureFile } from './lectureFile';

export type GetContentSync200 = {
  grades?: Grade[];
  terms?: Term[];
  modules?: Module[];
  subjects?: Subject[];
  lectures?: Lecture[];
  questions?: Question[];
  choices?: Choice[];
  questionSources?: QuestionSourceTag[];
  lectureVideos?: LectureVideo[];
  lectureFiles?: LectureFile[];
  nextCursor?: string;
};
