/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { GetStudentGradesWithTerms200ItemTermsItem } from './getStudentGradesWithTerms200ItemTermsItem';

export type GetStudentGradesWithTerms200Item = {
  id?: string;
  name?: string;
  terms?: GetStudentGradesWithTerms200ItemTermsItem[];
};
