/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { LectureDetailsSubject } from './lectureDetailsSubject';
import type { LectureVideo } from './lectureVideo';
import type { LectureFile } from './lectureFile';
import type { Question } from './question';

export interface LectureDetails {
  id?: string;
  subjectId?: string;
  name?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  subject?: LectureDetailsSubject;
  lectureVideos?: LectureVideo[];
  lectureFiles?: LectureFile[];
  questions?: Question[];
}
