/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PatchAdminStudyUnitsIdBodyType = typeof PatchAdminStudyUnitsIdBodyType[keyof typeof PatchAdminStudyUnitsIdBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchAdminStudyUnitsIdBodyType = {
  lecture: 'lecture',
  section: 'section',
} as const;
