/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchStudentCasesIdBodyCategory } from './patchStudentCasesIdBodyCategory';

export type PatchStudentCasesIdBody = {
  category?: PatchStudentCasesIdBodyCategory;
  title?: string;
  content?: string;
  answer?: string;
};
