/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchStudentTasksIdBodyTaskType } from './patchStudentTasksIdBodyTaskType';
import type { PatchStudentTasksIdBodyStatus } from './patchStudentTasksIdBodyStatus';
import type { PatchStudentTasksIdBodyZekrTask } from './patchStudentTasksIdBodyZekrTask';
import type { PatchStudentTasksIdBodyWirdTask } from './patchStudentTasksIdBodyWirdTask';

export type PatchStudentTasksIdBody = {
  taskType?: PatchStudentTasksIdBodyTaskType;
  status?: PatchStudentTasksIdBodyStatus;
  /** @nullable */
  zekrTask?: PatchStudentTasksIdBodyZekrTask;
  /** @nullable */
  wirdTask?: PatchStudentTasksIdBodyWirdTask;
};
