/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PatchAdminQuestionsBulkAssignTelegramRangeBodySourceTypesItem = typeof PatchAdminQuestionsBulkAssignTelegramRangeBodySourceTypesItem[keyof typeof PatchAdminQuestionsBulkAssignTelegramRangeBodySourceTypesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchAdminQuestionsBulkAssignTelegramRangeBodySourceTypesItem = {
  previous_exam: 'previous_exam',
  doctor_confirmation: 'doctor_confirmation',
  owner: 'owner',
  team_expectation: 'team_expectation',
} as const;
