/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PatchStudentTasksIdBodyTaskType = typeof PatchStudentTasksIdBodyTaskType[keyof typeof PatchStudentTasksIdBodyTaskType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchStudentTasksIdBodyTaskType = {
  zekr: 'zekr',
  wird: 'wird',
} as const;
