/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PatchStudentNotesIdBodyType = typeof PatchStudentNotesIdBodyType[keyof typeof PatchStudentNotesIdBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchStudentNotesIdBodyType = {
  note: 'note',
  recurring_question: 'recurring_question',
  summary: 'summary',
} as const;
