/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PatchAdminUsersIdBodyRole = typeof PatchAdminUsersIdBodyRole[keyof typeof PatchAdminUsersIdBodyRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchAdminUsersIdBodyRole = {
  admin: 'admin',
  student: 'student',
} as const;
