/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PatchAdminQuestionsBulkAssignStudyUnitBodySourceTypesItem = typeof PatchAdminQuestionsBulkAssignStudyUnitBodySourceTypesItem[keyof typeof PatchAdminQuestionsBulkAssignStudyUnitBodySourceTypesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchAdminQuestionsBulkAssignStudyUnitBodySourceTypesItem = {
  previous_exam: 'previous_exam',
  doctor_confirmation: 'doctor_confirmation',
  owner: 'owner',
  team_expectation: 'team_expectation',
  data: 'data',
} as const;
