/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchAdminUsersIdBodyRole } from './patchAdminUsersIdBodyRole';

export type PatchAdminUsersIdBody = {
  name?: string;
  email?: string;
  password?: string;
  role?: PatchAdminUsersIdBodyRole;
  termId?: string;
};
