/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchStudentNotesIdBodyType } from './patchStudentNotesIdBodyType';

export type PatchStudentNotesIdBody = {
  type?: PatchStudentNotesIdBodyType;
  content?: string;
  /** @nullable */
  sourceQuestionId?: string | null;
};
