/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { PostStudentCasesBodyCategory } from './postStudentCasesBodyCategory';

export type PostStudentCasesBody = {
  lectureId: string;
  category: PostStudentCasesBodyCategory;
  title: string;
  content: string;
  answer?: string;
};
