/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PostStudentNotesBodyType = typeof PostStudentNotesBodyType[keyof typeof PostStudentNotesBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostStudentNotesBodyType = {
  note: 'note',
  recurring_question: 'recurring_question',
  summary: 'summary',
} as const;
