/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PostStudentTasksBodyStatus = typeof PostStudentTasksBodyStatus[keyof typeof PostStudentTasksBodyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostStudentTasksBodyStatus = {
  pending: 'pending',
  in_progress: 'in_progress',
  done: 'done',
  missed: 'missed',
} as const;
