/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PostStudentCasesBodyCategory = typeof PostStudentCasesBodyCategory[keyof typeof PostStudentCasesBodyCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostStudentCasesBodyCategory = {
  case: 'case',
  disease: 'disease',
  drug: 'drug',
} as const;
