/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PostAdminUsersBodyRole = typeof PostAdminUsersBodyRole[keyof typeof PostAdminUsersBodyRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAdminUsersBodyRole = {
  admin: 'admin',
  student: 'student',
} as const;
