/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { PostAdminQuestionsBodyQuestionType } from './postAdminQuestionsBodyQuestionType';
import type { PostAdminQuestionsBodyChoicesItem } from './postAdminQuestionsBodyChoicesItem';

export type PostAdminQuestionsBody = {
  questionText?: string;
  explanation?: string;
  questionType?: PostAdminQuestionsBodyQuestionType;
  source?: string;
  sourceId?: string;
  /** @nullable */
  subjectId?: string | null;
  /** @nullable */
  telegramMessageId?: number | null;
  writtenAnswer?: string;
  choices?: PostAdminQuestionsBodyChoicesItem[];
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  answerImageUrl?: string | null;
};
