/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PostStudentDevicesRegisterBodyPlatform = typeof PostStudentDevicesRegisterBodyPlatform[keyof typeof PostStudentDevicesRegisterBodyPlatform];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostStudentDevicesRegisterBodyPlatform = {
  ios: 'ios',
  android: 'android',
} as const;
