/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { PostStudentTasksBodyTaskType } from './postStudentTasksBodyTaskType';
import type { PostStudentTasksBodyStatus } from './postStudentTasksBodyStatus';
import type { PostStudentTasksBodyZekrTask } from './postStudentTasksBodyZekrTask';
import type { PostStudentTasksBodyWirdTask } from './postStudentTasksBodyWirdTask';

export type PostStudentTasksBody = {
  taskType: PostStudentTasksBodyTaskType;
  /** @nullable */
  startTime?: string | null;
  /** @nullable */
  endTime?: string | null;
  /** @nullable */
  consumedTime?: number | null;
  /** @nullable */
  estimatedTime?: number | null;
  status: PostStudentTasksBodyStatus;
  /** @nullable */
  achievedFrom?: string | null;
  /** @nullable */
  zekrTask?: PostStudentTasksBodyZekrTask;
  /** @nullable */
  wirdTask?: PostStudentTasksBodyWirdTask;
};
