/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PostAdminStudyUnitsBodyType = typeof PostAdminStudyUnitsBodyType[keyof typeof PostAdminStudyUnitsBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAdminStudyUnitsBodyType = {
  lecture: 'lecture',
  section: 'section',
} as const;
