/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthRegisterBody = {
  name?: string;
  email?: string;
  password?: string;
};
