/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type PostStudentTasksCompleteStudyBodyActivityType = typeof PostStudentTasksCompleteStudyBodyActivityType[keyof typeof PostStudentTasksCompleteStudyBodyActivityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostStudentTasksCompleteStudyBodyActivityType = {
  watch: 'watch',
  solve: 'solve',
  revision: 'revision',
} as const;
