/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionSource } from './questionSource';

export interface Question {
  id?: string;
  /** @nullable */
  studyUnitId?: string | null;
  /** @nullable */
  createdBy?: string | null;
  questionText?: string;
  explanation?: string;
  source?: QuestionSource;
  createdAt?: string;
  updatedAt?: string;
}
