/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionSourceTagSourceType } from './questionSourceTagSourceType';

export interface QuestionSourceTag {
  id?: string;
  questionId?: string;
  sourceType?: QuestionSourceTagSourceType;
  updatedAt?: string;
  /** @nullable */
  deletedAt?: string | null;
}
