/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type QuestionSource = typeof QuestionSource[keyof typeof QuestionSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionSource = {
  telegram_auto: 'telegram_auto',
  admin_manual: 'admin_manual',
} as const;
