/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { StructuredModule } from './structuredModule';

export interface StructuredTerm {
  id?: string;
  gradeId?: string;
  name?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  modules?: StructuredModule[];
}
