/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { Lecture } from './lecture';

export interface StructuredSubject {
  id?: string;
  moduleId?: string;
  name?: string;
  createdAt?: string;
  updatedAt?: string;
  lectures?: Lecture[];
}
