/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { StudyUnitType } from './studyUnitType';

export interface StudyUnit {
  id?: string;
  subjectId?: string;
  name?: string;
  description?: string;
  type?: StudyUnitType;
  order?: number;
  createdAt?: string;
  updatedAt?: string;
}
