/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { StudyUnitDetailsType } from './studyUnitDetailsType';
import type { StudyUnitDetailsSubject } from './studyUnitDetailsSubject';
import type { LectureVideo } from './lectureVideo';
import type { LectureFile } from './lectureFile';
import type { Question } from './question';

export interface StudyUnitDetails {
  id?: string;
  subjectId?: string;
  name?: string;
  description?: string;
  type?: StudyUnitDetailsType;
  order?: number;
  createdAt?: string;
  updatedAt?: string;
  subject?: StudyUnitDetailsSubject;
  lectureVideos?: LectureVideo[];
  lectureFiles?: LectureFile[];
  questions?: Question[];
}
