/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export type StudyUnitDetailsType = typeof StudyUnitDetailsType[keyof typeof StudyUnitDetailsType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudyUnitDetailsType = {
  lecture: 'lecture',
  section: 'section',
} as const;
