/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */
import type { UserAuthProvider } from './userAuthProvider';
import type { UserRole } from './userRole';

export interface User {
  id?: string;
  name?: string;
  email?: string;
  authProvider?: UserAuthProvider;
  role?: UserRole;
  /** @nullable */
  termId?: string | null;
}
