/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export interface VideoProgress {
  id?: string;
  userId?: string;
  lectureVideoId?: string;
  positionSeconds?: number;
  updatedAt?: string;
}
