/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Manhaj API
 * Offline-First Student Question Bank API
 * OpenAPI spec version: 1.0.0
 */

export interface Zekr {
  id?: string;
  text?: string;
  transliteration?: string;
  meaning?: string;
  source?: string;
  defaultCount?: number;
  createdAt?: string;
  updatedAt?: string;
}
